import random
names = [
 'Aarav', 'Vivaan', 'Aditya', 'Arjun', 'Rohan',
 'Rahul', 'Amit', 'Vikas', 'Suresh', 'Rajesh',
 'Priya', 'Anjali', 'Pooja', 'Sneha', 'Neha',
 'Shah Rukh Khan', 'Salman Khan', 'Aamir Khan',
 'Lion', 'Tiger', 'Elephant',
 'John', 'Michael', 'Emma', 'Olivia'
]


actions = actions = [
    "run",
    "walk",
    "jump",
    "sit",
    "stand",
    "sleep",
    "eat",
    "drink",
    "cook",
    "read",
    "write",
    "draw",
    "paint",
    "sing",
    "dance",
    "swim",
    "drive",
    "ride",
    "climb",
    "crawl",
    "laugh",
    "cry",
    "smile",
    "talk",
    "listen",
    "watch",
    "think",
    "learn",
    "teach",
    "study",
    "play",
    "work",
    "travel",
    "shop",
    "clean",
    "wash",
    "build",
    "fix",
    "open",
    "close",
    "throw",
    "catch",
    "kick",
    "push",
    "pull",
    "lift",
    "carry",
    "search",
    "find",
    "hide",
    "help",
    "call",
    "text",
    "email",
    "code",
    "debug",
    "design",
    "create",
    "delete",
    "copy",
    "paste",
    "print",
    "save",
    "upload",
    "download",
    "click",
    "scroll",
    "type",
    "calculate",
    "measure",
    "count",
    "buy",
    "sell",
    "pay",
    "borrow",
    "lend",
    "grow",
    "plant",
    "harvest",
    "explore",
    "discover",
    "celebrate",
    "exercise",
    "meditate",
    "relax",
    "wait",
    "arrive",
    "leave",
    "start",
    "finish",
    "win",
    "lose",
    "remember",
    "forget",
    "repair",
    "organize",
    "pack",
    "unpack",
    "decorate",
    "practice"
]

places = [
    "New York",
    "London",
    "Paris",
    "Tokyo",
    "Sydney",
    "Dubai",
    "Singapore",
    "Toronto",
    "Berlin",
    "Rome",
    "Moscow",
    "Beijing",
    "Seoul",
    "Bangkok",
    "Istanbul",
    "Cape Town",
    "Los Angeles",
    "Chicago",
    "Miami",
    "San Francisco",
    "Delhi",
    "Mumbai",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Jaipur",
    "Indore",
    "Bhopal",
    "Ahmedabad",
    "Lucknow",
    "Surat",
    "Nagpur",
    "Mandsaur",
    "Udaipur",
    "Jodhpur",
    "Goa",
    "Shimla",
    "Manali",
    "Darjeeling",
    "Leh",
    "Agra",
    "Varanasi",
    "Amritsar",
    "Mysuru",
    "Kochi",
    "Jaipur Fort",
    "Taj Mahal",
    "Mount Everest",
    "Grand Canyon",
    "Niagara Falls",
    "Amazon Rainforest",
    "Sahara Desert",
    "Swiss Alps",
    "Great Wall of China",
    "Eiffel Tower",
    "Golden Gate Bridge",
    "Statue of Liberty",
    "Times Square",
    "Central Park",
    "Disneyland",
    "Yellowstone National Park",
    "Lake Tahoe",
    "Maldives",
    "Bali",
    "Phuket",
    "Santorini",
    "Venice",
    "Prague",
    "Vienna",
    "Barcelona",
    "Lisbon",
    "Athens",
    "Cairo",
    "Rio de Janeiro",
    "Buenos Aires",
    "Mexico City",
    "Honolulu",
    "Auckland",
    "Reykjavik",
    "Antarctica",
    "North Pole",
    "South Pole",
    "Amazon River",
    "Ganga River",
    "Nile River",
    "Himalayas",
    "Andaman Islands",
    "Lakshadweep",
    "Ooty",
    "Rishikesh",
    "Haridwar",
    "Nainital",
    "Khajuraho",
    "Sanchi",
    "Orchha",
    "Pachmarhi",
    "Kanha National Park",
    "Bandhavgarh National Park"
]

while True:
    name = random.choice(names)
    places= random.choice(places)
    actions = random.choice(actions)
    print( f"{name}  {actions}  at {places}")
    choice = input("DO you want to another headline? yes/no"  ).lower().strip()
    if choice == 'no':
        break

 


    


   

 